# Generated by Django 5.1.3 on 2024-11-19 10:41

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='blog',
            new_name='blog_post',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'blog_post')},
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
